import { Footer, NavBar } from "./HewsonPage";

export type Post = {
  id: number;
  title: string;
  tag: string;
  excerpt: string;
  heroTitle?: string;
  sections: { heading?: string; paragraphs: string[] }[];
};

export const POSTS: Post[] = [
  { id: 1, title: "The Founder/CEO, Hewson Consulting Services", tag: "Profile", excerpt: "Mr. Matthew A. Aziegbe - BSc, FIMC, MNIVS, MNCS, CMC, RSV. A multifaceted fellow, consultant and industry leader, renowned as strategic growth architect & technical CRE advisor to real-estate & allied corporate players.", sections: [
    { paragraphs: ["Mr. Matthew A. Aziegbe\nBSc, FIMC, MNIVS, MNCS, RSV", "A multifaceted fellow, consultant and industry leader, identified as strategic growth architect & technical CRE advisor. Astute professionally certified management analyst, accredited techie, chartered estate surveyor and registered valuer."] },
    { heading: "Academic & Professional Background", paragraphs: ["• Graduate with Honours Degree in Geography with Economics minor, obtained from the University of Benin, Nigeria.\n• Holder of Extension Certificate in Electronic Data Processing & Computer Programing from the University of Lagos, Nigeria.\n• Holder the Final Professional Diploma in Estate Management & Valuation from the Nigerian Institution of Estate Surveyors & Valuers.\n• Full Member of The Nigerian Institution of Estate Surveyors & Valuers.\n• Fellow of the Institute of Management Consultants (Nigeria).\n• Full Member of the Nigeria Computer Society (the National IT Chartered Body). \n• Registered Member of Estate Surveyors & Valuers Registration Board of Nigeria. \n• Holder of Chartered status as Certified Management Consultant."] },
    { heading: "Public & Private Sector Career Path", paragraphs: ["• Started his career with then Schools Management Board of Lagos State after graduation, and later joined the National Productivity Centre, a federal parastatal offering productivity audit & management training, consultancy & facilitation as a Senior Productivity Officer.\n• Thereafter, he crossed over to the private sector, charting a new course under professional practice. He trained under three registered estate consulting firms to achieve chartered status, rising to become Associate Partner.\n• Consequently, he moved to corporate real estate, and worked with high net-worth companies. First engagement had Foluso Properties Ltd (Arm of Rufus Giwa's RFG Group) as General Estate Manager; then Crown Realties Plc (Estate Developers & Investors) as Manager/ Sales Surveyor; and later Nuel Ojei Holdings (Diversified Conglomerate) as Facility Manager.\n• In between, he deepened his capability in technology by serving with Leading Edge Limited, a Systems & IT Consulting outfit as Coordinator of Corporate Training, where he facilitated training for Central Bank and business with NEPA Abuja, amongst others.\n• While under employment in estate practice, he co-piloted a PPP joint venture between the Federal Ministry of Works & Housing and two collaborating firms on land regularization exercise in Alimosho Area, Lagos.\n• Besides Hewson Consulting, he operates the firm of Aigbebhalu Aziegbe & Co, a chartered estate practice."] },
    { heading: "Experience Highlight", paragraphs: ["His work experience spans different public service and private sector organisations.\n• Occupied teaching, productivity, sales, marketing, IT, strategy & training positions beside real estate roles.\n• Deployed his resource bent featuring cross-functional skill, analytical thinking, creativity and strategic drive.\n• Held central level positions in management, revenue generation and operations field.\n• Leveraged mixed background in delivering smart solutions that generated value creation.\n• Addressed critical enterprise, system, manpower & project needs effectively."] },
    { heading: "Consultancy Thrust", paragraphs: ["His consulting works recalibrate strategy, strengthen IT functionality and accelerate sales productivity, besides reenforcing team development, project outcome and management process. Essentially, his expertise help bridge the gap between applied management, IT system and real-estate business operations, which enhance estate projects, asset performance and financial ROI metrics."] },
    { heading: "Service Record", paragraphs: ["His consulting interest resonates from experience in central level positions. In 2018, he founded Hewson Consulting, an independent niche consultancy that focuses on businesses across real-estate & allied industry. He has helped executive teams, developers and companies move past operational frictions, marketing challenges, and technical hurdles. Effective at scaling revenue and boosting ROI beyond 2x."] },
    { heading: "Nominations & Awards", paragraphs: ["Serial nominee for attainment in scholarship, leadership & profession, and multiple award recipient under corporate and personal brand."] },
    { heading: "Regular Pastime", paragraphs: ["He enjoys periodicals, musicals, networking, workouts & sightseeing", "Official Email Contact: m.aziegbe@hewson-consult.com"] },
  ] },
  { id: 2, title: "Real Estate Economics & Its Perspective View", tag: "Analysis", excerpt: "Both investors and analysts see investment in real estate as viable since they hardly nosedive, but regularly experience capital appreciation. In some climes, even without external consultants, they experience growth.", sections: [
    { paragraphs: ["Both investors and analysts see investment in real estate as viable since they hardly nosedive, but regularly experience capital appreciation. In some climes, even without external consultants, they experience growth. Therefore, most property developers/ investors tend to relegate the necessity for expert involvement in error while relying on self-management and sometimes even unqualified persons.", "Input of experts who understand the technicalities of real estate are oftentimes ignored because these property owners erroneously count on capital appreciation over time as index of good investment and secure income. The omission therein is highlighted by real estate economics which posits that capital appreciation along with inflationary rate determine real value of money in the future. Our studies show that in some segments of the real estate market, net difference display a negative index even when there is relative capital appreciation.", "As a low-risk investment, real estate returns in some regions is currently being challenged by extraneous factors, such as economic regression, socio-political unrest and even climatic outpouring and pandemic outbreak. Such occurrence calls for periodic holistic audit at critical intervals in order to ascertain state of performance of property portfolio for strategic or proactive reasons, and remedial action where necessary. Such sidelined experts understand how sensitivity and risk analysis help real-estate portfolios in maintaining steady investment course.", "High corporate net-worth investors and stakeholders in real-estate sector and their managers should, as a necessity, give consideration to periodic adjustment in their property investment portfolios, according to structural changes in economy. The interplay of economic forces causes oscillation investment index in different sectors with attendant implications on real-estate and its segments, which invariably demands realignment at intervals.", "Written by:\nMatthew A. Aziegbe, CEO"] },
  ] },
  { id: 3, title: "Our Real-Estate Business Consulting Purpose", tag: "Insight", excerpt: "At Hewson Consulting, we offer services that are fundamental to enterprise growth and their management process. Our specialty lies in assisting built environment & real-estate sector companies with specialized services.", sections: [
    { paragraphs: ["At Hewson Consulting, we offer services that are fundamental to enterprise growth and their management process. Our specialty lies in assisting built environment & real-estate sector companies with specialized services, including market research, strategy formulation, IT optimization, project appraisal, finance structuring, sales effectiveness and business modelling.", "Organizations which downplay these fundamental areas of operation will shortchange themselves, and would hardly expand to full capacity since these factors determine growth. The effectiveness of management structure, for instance, dictates revenue generation capacity while the marketing and sales function dictates market penetration, nay profitability. Commercial estate development companies require a balance between their development works and management advisory.", "While other investment options like shares, mutual funds and even bank deposit and pensions are placed under corporate expert guidance, same cannot be said of most capital investment in real estate. Despite the huge financial outlay expended on real-estate and project activities, which oftentimes over shadow other forms of investment outlay, they are, more often than not, managed without adequate structure, and even by unqualified field personnel at managerial and supervisory level.", "While some operators appreciate the importance of engaging technical partners for advisory, others do not. The non-involvement of specialists is often at the detriment of their investments, as evidenced in shortfalls in expected earnings, avoidable void periods, asset life circle decline and several other negative indices. The beneficial effect of expert involvement provides impetus for investment growth, extended asset life and corporate expansion.", "Our specialists provide real-estate & allied companies with leading-edge support that meets acceptable global standard. This assistance enables organizations and their personnel to perform in the most productive way, thereby aiding optimal returns on investment and accelerated growth.", "As a one-stop CRE resource centre, we deliver smart solutions across business and technical divide. Whether you are a CRE/asset manager seeking to surpass set targets or a CEO focused on portfolio/ asset performance or even sales, our knowhow offer guide. We ensure your operations, team and project run smarter, faster and higher.", "Written by:\nMatthew A. Aziegbe, CEO"] },
  ] },
  { id: 4, title: "Real Benefits of Engaging Our Practice", tag: "Service", excerpt: "Hewson Consulting enables real-estate owners, developers, funders, investors and everyone with considerable real estate interest to consolidate process, enterprise growth & investment hold.", sections: [
    { paragraphs: ["Hewson Consulting enables real-estate owners, developers, funders, investors and everyone with considerable real estate interest to consolidate process, enterprise growth and investment hold. We provide the technical inputs required to translate project concepts into physical existence, and equally offer counterpart business support services as a one-stop solutions center.", "Our experts ease decision making process for executives and promote asset life cycle through our involvement as consultants. Our knowhow allows operators to leverage on existing real-estate assets as resource for acquisition of further assets. Our primary focus centers on helping field operators to improve their corporate brand, profitability and growth. The benefits of our consultancy support are highlighted below"] },
    { heading: "Functional Benefits", paragraphs: ["• We offer market research that provide vital information through thorough field investigation and survey, which promote growth assurance. We believe that fundamentals help executives define direction while analytics enable businesses make informed decisions.\n• We provide our clients with bankable documents, which include deep feasibility & viability reports required by financial institutions for granting development finance. We examine other alternative funding arrangement and advice on most appropriate finance options.\n• We assist in structuring projects for maximum profit outcome using our development model, which phantom in several factors. Ours inculcate location analysis, land-use matrix, architectural design implication, facility provision level, information system, legal factors and tax minimization.\n• We formulate core strategies, which revolve around revenue scaling, pivoting and market entry, amongst others. All geared towards helping companies achieve and sustain competitive edge. Besides, we refine existing ones, and, where necessary, proffer innovative changes that supplement companies’ efforts.\n• We offer business IT support that enables senior executives perform difficult tasks effortlessly, and deliver on their products and services. Thus, actualizing project schemes as planned, meeting financial projection and surpassing growth expectation."] },
    { heading: "Practical Benefits", paragraphs: ["• Specialist business investment advisory\n• Guaranteed pre-determined profit level\n• Higher property income generation capacity\n• Reduced lease occupancy/ void ratio\n• Effective property branding approach\n• Improved open market sales value outcome\n• Suitable information systems integration\n• Available local & foreign capital injection\n• Improved asset life-circle and returns\n• Statutory property tax reduction advisory\n• Total business re-engineering and growth\n• Improved corporate image branding\n• Enhanced corporate net worth value\n• Expert intervention and facilitation\n• Unfailing project turn-around", "Written by:\nThe Research Team,\nHewson Consulting Services"] },
  ] },
  { id: 5, title: "Building Sustainable Estate Portfolio in Stages", tag: "Advice", excerpt: "In order to gradually build and expand one’s property investment portfolio, the individual or corporate entity must be intentional and strategic in approach.", sections: [
    { paragraphs: ["In order to gradually build and expand one’s property investment portfolio, the individual or corporate entity must be intentional and strategic in approach."] },
    { heading: "Basic Factors To consider", paragraphs: ["Firstly, every property portfolio investor should start off with a corporate vision statement in order to give effect to purpose. Such articulation will enable team members to work in unison to achieve set goals. Both personal and corporate investors must drive conviction with signpost that resonates with vision statement, such as: invest in asset not liability Thus, every property will be evaluated on its strength as either a asset or liability.", "For some investors, the challenge they encounter at some point could be frustrating, leading to disposal of property. This scenario is mostly seen where owners erroneously believe that expert involvement is not necessary. Such owners see self-decision, own management or engagement of quacks as property manager to be adequate. The challenges they face under this arrangement arise mostly from uninformed decision making.", "Besides other hurdles, such investors get caught up in confrontation with uncooperative tenants who stubbornly renege on tenancy terms, resulting in colossal rental defaults. In advanced climes, the laws are strict, and such issues are quickly dispatched with. But in others like Nigeria, the law appears to be tilted against landlords, thus causing frustration at scale. Not only does engagement of property management experts, who practice as chartered estate surveyors & valuers, limit such occurrence, they help property owners achieve optimal rental returns."] },
    { heading: "Follow Conservative Property Investment Process", paragraphs: ["Generally, players must be swift and decisive, and learn to trust their instinct over time besides hiring technical partners for advice. Those investors who know what they want have bought lands, upon sighting of genuine Certificate-of-Occupancy and layout plans, without even stepping on the land, knowing the area in question will satisfy a current or future demand.", "However, where due diligence is absent, buyers have occasionally lost possession of properties for lack of adequate legal cover. As every vacant land becomes visible and more valuable with time, intervening issues may arise bothering on documentation, non-compliance, locus standi of original seller, right of original owner, and even statutory right of way. All of these call for proper legal documentation upon purchase, be it developable land or improved property."] },
    { heading: "Escue Emotional Attachment To Property", paragraphs: ["As a rule, owners must never be sentimentally attached to any land. Property should be viewed as any other product that is an article of trade. When a property is becoming an irredeemable asset liability, the owner will do well to dispose. Owners must, however, differentiate those properties without immediate value but capable of great future returns from those that satisfy no purpose. The guiding principle here is professional judgement which require market insight.", "Those building portfolio as investment must therefore be incisive, they must know when to exit a particular market (geographic region) or sub-sector (residential, commercial, industrial, office, and others) to redirect resources to others."] },
    { heading: "Local & International Market Alternatives", paragraphs: ["Building portfolio does not necessarily have to be confined to local market. There is a world of opportunities in the international market. However, to invest overseas, you must know local practices, applicable laws, property policies and peculiarities that influence property returns.", "Discerning property investors in Nigeria know that due to devaluation of dollar to naira exchange rate, it is often better to invest in overseas properties under particular circumstances.", "The need to properly appraise investment through specialist must not be under estimated. In Britain, for instance, one pays all forms of taxes including capital gains which make investment there comparatively less lucrative. Whereas in Dubai, such conditions hardly exist, rather they extent incentives to foreign investors."] },
    { heading: "Summary & Conclusion", paragraphs: ["This presentation is intended to enlighten new investors on processes for building and expanding portfolio under professional support of specialist who provide consultancy guide, establish growth strategy, introduce fresh perspectives, and unlock hidden opportunities.", "At Hewson Consulting, we play the pivotal role of technical partner, leveraging our expertise to empower you achieve your property investment goals.", "Written by:\nMatthew A. Aziegbe, CEO"] },
  ] },
  { id: 6, title: "Helping CRE Businesses Achieve Revenue Growth", heroTitle: "Helping CRE Operators Achieve Revenue Growth", tag: "Service", excerpt: "Hewson Consulting offers specialized growth consultancy services for companies, CEOs, developers and investors in the real estate & allied industry. Our experts have years of experience that can assist you.", sections: [
    { paragraphs: ["Hewson Consulting offers specialized growth consultancy services for companies, CEOs, developers & players in the real-estate & allied industry.", "Our experts have years of experience that can assist you (1) identify new opportunities & approach for growth (2) streamline your operations & processes (3) package bankable reports required by lending institutions for granting project finance (4) expand your business via our technical support and (5) enhance your investment returns.", "Our consulting forte transverse market research & analysis, strategic planning, financial modelling, project appraisal and land use evaluation & advisory. We equally help organizations with business development, strategy, IT deployment, staffing solutions and stakeholder level engagement.", "We deploy multi-disciplinary team approach in addressing critical technical & business issues. Whether you are a large corporation or a small, local developer, we have the expertise to help you advance in today's competitive market.", "As strategic growth architects & technical CRE facilitators, we assist you navigate the complexities of the real-estate & allied industry. Our specialists provide you with higher order services that effectively fuel business growth & revenue boost."] },
    { heading: "Our Foundational 5-Cardinal Pillars", paragraphs: ["• Helping operators fix pressing issues across estate/asset value chain.\n• Crafting integrated business solutions for exceptional client experience.\n• Deploying multidisciplinary team approach with unrivalled field insight.\n• Offering niche expertise to aid operators navigate complex situations.\n• Fueling technical depth, business growth & revenue boost."] },
    { heading: "Hewson Consulting Outlook", paragraphs: [] },
    { heading: "1. Business Development Division", paragraphs: ["• Market Research & Industry Analysis\n• Business Modeling & Strategy Formulation\n• Process Improvement & Workflow Design\n• Manpower Training & Capacity Building\n• Executive Search & Recruitment Service\n• Growth Systematization & Structuring"] },
    { heading: "2. Technical Enterprise Division", paragraphs: ["• Project Evaluation & Fund brokerage\n• Property Marketing & Sales Effectiveness\n• Real-Estate Operations & IT Integration\n• Portfolio Management & Optimization\n• Land-use Informatics & Data Analytics\n• Business Valuations & Asset Advisory", "Contact us to know how our consultancy can benefit your company and help you achieve your business goals.", "Written by:\nThe Research Team,\nHewson Consulting Services"] },
  ] },
  { id: 7, title: "How Estate Companies Can Accelerate Progress", tag: "Advice", excerpt: "This question has often emerged in conversations with executives and operators in the course of service. I have carefully examined, and drawn conclusion from, successful business organizations across spectrum. Here are my thoughts", sections: [{ paragraphs: ["This question has often emerged in conversations with executives and operators in the course of service. In response, I have carefully examined, and drawn conclusion from, successful business organizations across spectrum.", "To ascend in ranking, one fundamental factor that operators in the real-estate & allied industry must appreciate is that they operate in a dynamic market, where their relative position to competitors is determined not only by expertise, but a mix of interactive factors.", "Firstly, a top-ranking position needs acceptance as industry expert. Basically, this requires having exceptional products and services with effective delivery system; paying attention to likeability factors that enhance firm's perception rating; optimizing your industry presence, seeking recognition through interactions, events and occasions; elevating brand awareness by deploying media promotion; collaborating with specialists; and inculcating global best practices", "In addition, I advise that executives deploy networking; develop a lifestyle of socialization with stakeholders as catalytic factor, enter into strategic alliance with international firms; incorporate event sponsorship for corporate image boost; and continually build trust for third-party endorsement.", "It is also compelling for CEOs to engage in purposeful self-branding that enhance their presence. The personal brand of chief executives has been known to impact positively on the general growth of their organization.", "Paying attention to these factors, as much as resources and time permit, can produce a combined synergy that places every organization on the journey to the forefront of their defined niche market.", "Such checklist helps operators to recognize areas requiring strategic focus, improvement and remedial action. Progressively, this framework propels companies into remarkable growth, and enable them become tier-1 player.", "Written by:\nMatthew A. Aziegbe, CEO"] }] },
  { id: 8, title: "Process Management As Efficiency Booster", tag: "Insight", excerpt: "Enterprise process management help companies achieve operational efficiency which maximizes output with minimal resource input. By identifying inherent bottlenecks and eliminating waste, businesses reduce costs and respond faster to improvement.", sections: [
    { paragraphs: ["Enterprise process management help companies achieve operational efficiency which maximizes output with minimal resource input. By identifying inherent bottlenecks and eliminating waste, businesses reduce avoidable costs and respond faster to improvement. This ensures long-term profitability, efficiency and sustainable growth."] },
    { heading: "The Difference: Efficiency Vs Effectiveness:", paragraphs: ["Knowing the difference between efficiency and effectiveness is critical for understanding process management in general:\n1. Efficiency: Doing things right. This is all about speed, resource utilization, and general cost control, which provide basic operational growth alignment.\n2. Effectiveness: Doing the right things. It ensures that the outputs align with the company's overall goals, emphasizing quality and customer satisfaction."] },
    { heading: "Why Process Management Matters:", paragraphs: ["Explicit process management ensures smooth, consistent execution across departments. When organizations manage processes effectively, they create predictable and repeatable results.\nKey benefits include:\n1. Cost Reduction: Minimizing wasted materials, idle time, and unnecessary tasks.\n2. Better Resource Allocation: Deploying time, labour, and capital as efficiently as possible.\n3. Enhanced Quality: Creating strict standards that result in consistent, top-notch products or services."] },
    { heading: "Top Strategies for Operational Efficiency:", paragraphs: ["(a) Process Mapping and Analysis\nBefore improving a workflow, you must understand its present state. Process mapping visually outlines all steps involved in an operation, making it easy to spot bottlenecks and redundancies. Methodologies like Value Stream Mapping (VSM) focus on removing non-value-adding steps", "(b) Leverage Technology and Automation\nTechnology is now the backbone of business operations. Implementing Robotic Process Automation (RPA) for repetitive, manual tasks reduces human error and frees up employees to focus on strategic work. Advanced analytics and Enterprise Resource Planning (ERP) tools provide real-time monitoring and forecasting capabilities.", "(c) Adopt Lean and Six Sigma Methodologies\nThese frameworks allow continuous improvement and waste reduction. Lean methodology eliminates waste, while Six Sigma relies on data-driven approaches to minimize defects and variations. Organizations that apply these principles report major improvements in efficiency.", "(d) Cultivate a Continuous Improvement Culture\nIt must be noted that operational efficiency is not a one-time project; it is an ongoing thing. Businesses must foster a culture that regularly reviews processes, solicits employee feedback, and remains agile to stay competitive."] },
    { heading: "How to Measure Success:", paragraphs: ["To ensure your strategies are working as required, you obviously need to track measurable Key Performance Indicators (KPIs):\n1. Cycle Time: The total time it usually takes to complete a specific process from start to finish provides basic insight.\n2. Operational Efficiency Ratio: This ratio is a financial metric that is used to evaluate operating expenses relative to net revenues.\n3. Resource Utilization: The percentage of resources, such as machinery and labour capacity, being used effectively.", "Written by:\nThe Research Team,\nHewson Consulting Services"] },
  ] },
  { id: 9, title: "Project Optimization Via Effective Process", tag: "Advice", excerpt: "Most developers often concentrate their efforts on the physical aspects, like building design, aesthetics, site operations, facility provisions & land-use pattern during planning. In contrast, the non-physical factors are seen as tangential. ", sections: [{ paragraphs: ["Most developers often concentrate their efforts on the physical aspects, like building design, aesthetics, site operations, facility provisions & land-use pattern during planning. In contrast, the non-physical factors which complement the physical, such as management structure, marketing/ sales alignment, software integration, are seen as tangential. Even detailed location analysis and pre-investment appraisal is sometimes also downplayed.\nThis oversight has derailed many development schemes, resulting in abandonment and unprofitability. While the physical is important, they are no longer enough to guarantee project success. The non-physical factors are equally important as they help minimize cost, reduce risk and protect outlay. Likewise, they guarantee inflow, minimize void, maximize ROI and sustain continuity. Their inclusion ensure projections are achieved and growth sustained.", "Smart decisions at the beginning founded on informed due process offer safeguard. The planning stage starts with location intelligence (LI) which pinpoint best location for development siting. This provides most beneficial location for the intended development. Where a particular land is subject of analysis, the focus shifts to determining its highest and best use, which provide most profitable use of particular sites within legal, financial, technical and social framework. The appraisal pinpoints the best option from a range of land use alternatives.", "The design stage should be after the appraisal by an estate surveyor & valuer, who is practically a land economist with deep perspective of appraisal issues. There are areas of overlap between the various members in the project team. However, in real estate analytics, the estate practitioner is miles ahead. It is therefore in the best interest of a developer to consult the estate surveyor & valuer first on high-stake real estate project. In this way their professional pre-investment appraisal would serve as pointer for project design.", "It is important for developers to conduct their project activities under corporate business structure. They should also incorporate the functional units - operations, strategy, technology, projects, manpower and finance - into their structure. The resultant synergy between these units on one hand and the physical and business factors on the other hand will accelerate business and revenue growth.", "Written by:\nMatthew A. Aziegbe, CEO"] }] },
  { id: 10, title: "Location Intelligence in Project Planning", tag: "Insight", excerpt: "There is always the need to incorporate spatial locational analysis before deciding on preferred choice of location for development projects. This operation calls for geospatial data analysis, and this should be a prelude to feasibility and viability appraisal.", sections: [{ paragraphs: ["There is always the need to incorporate spatial locational analysis before deciding on preferred choice of location for development projects. This operation calls for geospatial data analysis, and this should be a prelude to feasibility and viability appraisal. More often than not, developers have preconceived preference for specific location and particular land use, which sometimes negate optimum returns on their huge investment.", "Under due process, planning starts with geospatial analysis, which borders on location intelligence (LI) also called location analytics which help to determine best geographic location to site a real estate project. Location intelligence has on the flip side highest and best use, which determine most profitable land use permissible under financial, legal, technical and social framework. Both play vital roles in selection, and usually referenced in feasibility and viability reports as fundamental base.", "Expert examination often considers broad land use categories - residential, commercial, industrial, educational, recreational, etc. - before arriving at a decision. The elimination process involves simple qualitative test factors. We recommend that not more than three choices be made after this stage for in-depth study. Upon final selection, the sub-categories of the preferred choice come under quantitative test. With residential for example, sub-categories can include blocks of flats, bungalow units, multiple storey buildings, duplex or semi-detached houses and others to choose from.", "Where the developer's personal preference is final, the location appraisal is downplayed since they become non determinant. Where the examination of alternatives is open, the analyst is not restricted, so he has a whole range of options. He deploys location analytics that imbibe geospatial data juxtaposed in layers as instrument for selection. This initialization is not only important but needful.", "The intrusion of geographical insight is considered useful in location intelligence, which has always been deployed beyond land use matters. Even business planning engages location intelligence for operational decisions in sales & market expansion, supply chain & logistics, risk mitigation & asset protection, and several others.", "Hewson Consulting offers location intelligence as a service, for optimum site selection and highest and best use.", "Written by:\nMatthew A. Aziegbe, CEO"] }] },
];

function BlogHero({ title }: { title: string }) {
  return <section className="w-full bg-[#102a5f] px-4 py-14 md:py-16"><h1 className="mx-auto max-w-[1200px] text-center font-['Inter:Semi_Bold',sans-serif] text-[24px] font-semibold uppercase leading-tight text-white md:text-[30px]">{title}</h1></section>;
}

function BlogShell({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className="flex min-h-screen w-full flex-col bg-white"><NavBar topButtonLabel="Home" topButtonHref="/" /><BlogHero title={title} />{children}<Footer /></div>;
}

export default function BlogPage() {
  return <BlogShell title="Blog: Articles, News & Events"><main className="w-full px-4 py-7 md:px-9 md:py-8"><div className="grid grid-cols-1 md:grid-cols-2 md:divide-x divide-[#edf0f3]">{POSTS.map((post) => <article key={post.id} className="border-b border-[#edf0f3] px-0 py-6 md:px-6 md:py-5 first:pt-0 md:[&:nth-child(-n+2)]:pt-0"><h2 className="font-['Inter:Semi_Bold',sans-serif] text-[20px] font-semibold leading-tight text-[#232323] md:text-[23px]">{post.id}. {post.title}</h2><span className="mt-3 inline-block rounded-[4px] bg-[#e8f8fa] px-2 py-1 font-['Inter:Medium',sans-serif] text-[13px] text-[#363b4b]">{post.tag}</span><p className="mt-3 font-['Inter:Medium',sans-serif] text-[14px] leading-[1.65] text-[#565966] md:text-[16px]">{post.excerpt} <a href={`#/blog/${post.id}`} className="font-semibold text-[#232323] underline">Read More</a></p></article>)}</div></main><section className="grid grid-cols-1 gap-4 bg-[#f8f9fa] px-4 py-7 md:grid-cols-3 md:px-9"><a href="#/blog" className="rounded-[12px] border border-[#e8eaed] bg-white py-6 text-center font-['Inter:Semi_Bold',sans-serif] text-[17px] font-semibold text-[#232323]">Company Events & Training</a><a href="#/blog" className="rounded-[12px] border border-[#e8eaed] bg-white py-6 text-center font-['Inter:Semi_Bold',sans-serif] text-[17px] font-semibold text-[#232323]">Industry Trends & Updates</a><a href="#/awards" className="rounded-[12px] border border-[#e8eaed] bg-white py-6 text-center font-['Inter:Semi_Bold',sans-serif] text-[17px] font-semibold text-[#232323]">Corporate Awards & Honour</a></section></BlogShell>;
}

export function BlogPostPage({ postId }: { postId: number }) {
  const post = POSTS.find((item) => item.id === postId) ?? POSTS[0];
  return <BlogShell title={post.heroTitle ?? post.title}><main className="w-full px-4 py-7 md:px-10 md:py-8"><article className="mx-auto max-w-[1360px]">{post.sections.map((section, sectionIndex) => <section key={`${section.heading ?? "content"}-${sectionIndex}`} className={sectionIndex === 0 ? "" : "mt-7"}>{section.heading && <h2 className="font-['Inter:Semi_Bold',sans-serif] text-[20px] font-semibold uppercase text-[#232323] md:text-[23px]">{section.heading}</h2>}{section.paragraphs.map((paragraph, paragraphIndex) => <p key={paragraphIndex} className="mt-3 whitespace-pre-line font-['Inter:Medium',sans-serif] text-[15px] leading-[1.75] text-[#565966] first:mt-0 md:text-[17px]">{paragraph}</p>)}</section>)}<a href="#/blog" className="mt-9 inline-block rounded-[9px] bg-[#ff383c] px-6 py-3 font-['Inter:Semi_Bold',sans-serif] text-[17px] font-semibold text-white no-underline">Read More Articles</a></article></main></BlogShell>;
}

export function AwardsPage() {
  return <BlogShell title="Corporate Awards & Honour"><main className="w-full px-4 py-7 md:px-10 md:py-8"><article className="mx-auto max-w-[1360px]"><h2 className="font-['Inter:Semi_Bold',sans-serif] text-[20px] font-semibold text-[#232323] md:text-[23px]">Mr. Matthew A. Aziegbe <span className="ml-2 text-[15px] font-medium">BSc, FIMC, MNIVS, MNCS, RSV</span></h2><p className="mt-4 font-['Inter:Medium',sans-serif] text-[15px] leading-[1.75] text-[#565966] md:text-[17px]">A multifaceted fellow, consultant and industry leader, identified as strategic growth architect and technical CRE advisor.</p><h3 className="mt-7 font-['Inter:Semi_Bold',sans-serif] text-[20px] font-semibold uppercase text-[#232323]">Nominations & Awards</h3><p className="mt-3 font-['Inter:Medium',sans-serif] text-[15px] leading-[1.75] text-[#565966] md:text-[17px]">Serial nominee for attainment in scholarship, leadership and profession, and multiple award recipient under corporate and personal brand, including:</p><div className="mx-auto mt-7 max-w-[900px] text-center"><h4 className="font-['Inter:Semi_Bold',sans-serif] text-[19px] font-semibold text-[#232323]">“Most Innovative Process Management & Staffing Consultancy 2023 – Nigeria”</h4><p className="mt-3 text-[#565966]">• Awarded by AI Global Media Group with Corporate Vision Magazine, an international UK-based award body.</p><hr className="mx-auto my-6 max-w-[380px] border-[#edf0f3]"/><h4 className="font-['Inter:Semi_Bold',sans-serif] text-[19px] font-semibold text-[#232323]">“Most Innovative Process Management & Real-Estate Staffing Consultancy 2024 – Nigeria”</h4><p className="mt-3 text-[#565966]">• Awarded by AI Global Media Group with Corporate Vision Magazine, an international UK-based award body.</p></div><a href="#/blog" className="mx-auto mt-8 block w-fit rounded-[9px] bg-[#ff383c] px-6 py-3 font-['Inter:Semi_Bold',sans-serif] text-[17px] font-semibold text-white no-underline">Read More Articles</a></article></main></BlogShell>;
}
